language: haskell

env:
  matrix:
    - HPVER=2012.4.0.0
    - HPVER=2013.2.0.0
    - GHCVER=7.4.2
    - GHCVER=7.6.3
    - GHCVER=head
  global:
    - CABALVER=1.16
    - UBUNTU_PKGS="libgtk-3-dev libcairo2-dev python-docutils"
    - EXTRA_DEPS_PRE="gtk2hs-buildtools"
    - HEAD_DEPS="diagrams-core diagrams-lib diagrams-cairo diagrams-contrib diagrams-builder docutils"
    - EXTRA_DEPS="SVGFonts shake hakyll safe"
    - secure: "GvSd0Muvr60TAaiBKHuGwFcuGAy4j2gaIV0IK4f9O8rJNyJSRdEpwW9i1MUvY7bSLT0pIx9A7WHHjDPUrtyxRs9uHQ3DcQG8ZF2Nmwf0Mgdd5ehdYcO6EVWRDJsBwk6JqloD7t3tiKJTE7APVbzLiuxxskpddiOb1+q2NQPsSuc="

matrix:
  allow_failures:
    - env: GHCVER=head

before_install:
  - git clone http://github.com/diagrams/diagrams-travis travis
  - source travis/scripts/set_env.sh
  - ./travis/scripts/before_install.sh

install: ./travis/scripts/install-deps.sh

before_script: ghc --make Shake -threaded

script: ./Shake +RTS -N2 -RTS buildh

after_success:
  - export RSYNC_PASSWORD=$ENIAC_PASSWORD
  - rsync -r web/_site/* byorgey@eniac.seas.upenn.edu:public_html/diagrams-doc-HEAD/

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#diagrams"
    skip_join: true
    template:
      - "\x0313diagrams-doc\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
